[build]
publish = "public"
command = "npm run build && hugo --gc --minify"
functions="./functions"

[context.production.environment]
HUGO_VERSION = "v0.74.2"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.split1]
command = "hugo --gc --minify --enableGitInfo"

[context.split1.environment]
HUGO_VERSION = "v0.74.2"
HUGO_ENV = "production"

[context.deploy-preview]
command = "npm run build && hugo --gc --minify --buildFuture -b \"${DEPLOY_PRIME_URL}/\""
functions="./functions"

[context.deploy-preview.environment]
HUGO_VERSION = "v0.74.2"

[context.branch-deploy]
command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
HUGO_VERSION = "v0.74.2"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"

